#!/bin/sh

# Check if a local zshrc file exists and source it
if [ -f "$HOME/.config/zsh/.zshrc_local" ]; then
  source "$HOME/.config/zsh/.zshrc_local"
fi

# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# source
plug "$HOME/.config/zsh/aliases.zsh"
plug "$HOME/.config/zsh/exports.zsh"

# local plugins
plug "$HOME/.config/zsh/plugins/fnm.zsh"
plug "$HOME/.config/zsh/plugins/ghq-fzf.zsh"
plug "$HOME/.config/zsh/plugins/mise.zsh"
plug "$HOME/.config/zsh/plugins/mix-escripts.zsh"
plug "$HOME/.config/zsh/plugins/bun.zsh"
plug "$HOME/.config/zsh/plugins/docker.zsh"

# Load and initialise completion system
autoload -Uz compinit
compinit

# external plugins
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"

# direnv
# load and unload environment variables depending on the current directory
# checks for .envrc or .env files
eval "$(direnv hook zsh)"

# prompt
eval "$(starship init zsh)"
